CREATE TYPE "public"."account_type" AS ENUM('prop_challenge', 'prop_funded', 'live', 'demo');--> statement-breakpoint
CREATE TYPE "public"."challenge_status" AS ENUM('active', 'passed', 'failed');--> statement-breakpoint
CREATE TYPE "public"."drawdown_type" AS ENUM('trailing', 'static', 'eod');--> statement-breakpoint
CREATE TYPE "public"."emotional_state" AS ENUM('confident', 'fearful', 'greedy', 'neutral', 'frustrated', 'excited', 'anxious');--> statement-breakpoint
CREATE TYPE "public"."execution_type" AS ENUM('entry', 'exit', 'scale_in', 'scale_out');--> statement-breakpoint
CREATE TYPE "public"."exit_reason" AS ENUM('manual', 'stop_loss', 'trailing_stop', 'take_profit', 'time_based', 'breakeven');--> statement-breakpoint
CREATE TYPE "public"."import_source" AS ENUM('manual', 'csv');--> statement-breakpoint
CREATE TYPE "public"."instrument_type" AS ENUM('futures', 'forex');--> statement-breakpoint
CREATE TYPE "public"."payout_frequency" AS ENUM('weekly', 'bi_weekly', 'monthly');--> statement-breakpoint
CREATE TYPE "public"."strategy_rule_category" AS ENUM('entry', 'exit', 'risk', 'management');--> statement-breakpoint
CREATE TYPE "public"."trade_direction" AS ENUM('long', 'short');--> statement-breakpoint
CREATE TYPE "public"."trade_status" AS ENUM('open', 'closed');--> statement-breakpoint
CREATE TYPE "public"."trading_platform" AS ENUM('mt4', 'mt5', 'projectx', 'ninjatrader', 'other');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('user', 'admin');--> statement-breakpoint
CREATE TABLE "account_group" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "account_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"color" text DEFAULT '#6366f1',
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "account" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "account_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"name" text NOT NULL,
	"broker" text,
	"platform" "trading_platform" DEFAULT 'other' NOT NULL,
	"account_type" "account_type" DEFAULT 'live' NOT NULL,
	"initial_balance" numeric(20, 2) DEFAULT '0',
	"currency" text DEFAULT 'USD',
	"account_number" text,
	"is_active" boolean DEFAULT true,
	"is_default" boolean DEFAULT false,
	"notes" text,
	"color" text DEFAULT '#6366f1',
	"max_drawdown" numeric(10, 2),
	"drawdown_type" "drawdown_type",
	"daily_loss_limit" numeric(10, 2),
	"profit_target" numeric(10, 2),
	"consistency_rule" numeric(10, 2),
	"min_trading_days" integer,
	"challenge_start_date" timestamp with time zone,
	"challenge_end_date" timestamp with time zone,
	"challenge_status" "challenge_status",
	"profit_split" numeric(10, 2),
	"payout_frequency" "payout_frequency",
	"linked_account_id" integer,
	"group_id" integer,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ai_conversation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ai_conversation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"title" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ai_message" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ai_message_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"conversation_id" integer NOT NULL,
	"role" text NOT NULL,
	"content" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "filter_preset" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "filter_preset_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"name" text NOT NULL,
	"filters" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "strategy" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "strategy_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"color" text DEFAULT '#d4ff00',
	"entry_criteria" text,
	"exit_rules" text,
	"risk_parameters" text,
	"scaling_rules" text,
	"trailing_rules" text,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "strategy_rule" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "strategy_rule_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"strategy_id" integer NOT NULL,
	"text" text NOT NULL,
	"category" "strategy_rule_category" DEFAULT 'entry' NOT NULL,
	"order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tag" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"name" text NOT NULL,
	"color" text DEFAULT '#6366f1',
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "trade_execution" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trade_execution_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"trade_id" integer NOT NULL,
	"execution_type" "execution_type" NOT NULL,
	"price" numeric(20, 8) NOT NULL,
	"quantity" numeric(20, 8) NOT NULL,
	"executed_at" timestamp with time zone NOT NULL,
	"fees" numeric(20, 2) DEFAULT '0',
	"realized_pnl" numeric(20, 2),
	"notes" text,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "trade_rule_check" (
	"trade_id" integer NOT NULL,
	"rule_id" integer NOT NULL,
	"checked" boolean DEFAULT false NOT NULL,
	"checked_at" timestamp with time zone,
	CONSTRAINT "trade_rule_check_trade_id_rule_id_pk" PRIMARY KEY("trade_id","rule_id")
);
--> statement-breakpoint
CREATE TABLE "trade_screenshot" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trade_screenshot_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"trade_id" integer NOT NULL,
	"url" text NOT NULL,
	"caption" text,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "trade_tag" (
	"trade_id" integer NOT NULL,
	"tag_id" integer NOT NULL,
	CONSTRAINT "trade_tag_trade_id_tag_id_pk" PRIMARY KEY("trade_id","tag_id")
);
--> statement-breakpoint
CREATE TABLE "trade" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "trade_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"account_id" integer,
	"strategy_id" integer,
	"symbol" text NOT NULL,
	"instrument_type" "instrument_type" NOT NULL,
	"direction" "trade_direction" NOT NULL,
	"status" "trade_status" DEFAULT 'open' NOT NULL,
	"entry_price" numeric(20, 8) NOT NULL,
	"entry_time" timestamp with time zone NOT NULL,
	"exit_price" numeric(20, 8),
	"exit_time" timestamp with time zone,
	"quantity" numeric(20, 8) NOT NULL,
	"stop_loss" numeric(20, 8),
	"take_profit" numeric(20, 8),
	"stop_loss_hit" boolean DEFAULT false,
	"take_profit_hit" boolean DEFAULT false,
	"trailed_stop_loss" numeric(20, 8),
	"was_trailed" boolean DEFAULT false,
	"exit_reason" "exit_reason",
	"is_partially_exited" boolean DEFAULT false,
	"remaining_quantity" numeric(20, 8),
	"realized_pnl" numeric(20, 2),
	"fees" numeric(20, 2) DEFAULT '0',
	"net_pnl" numeric(20, 2),
	"setup_type" text,
	"emotional_state" "emotional_state",
	"notes" text,
	"rating" integer,
	"is_reviewed" boolean DEFAULT false,
	"import_source" "import_source" DEFAULT 'manual' NOT NULL,
	"external_id" text,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "user_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"openai_api_key" text,
	"anthropic_api_key" text,
	"google_api_key" text,
	"preferred_ai_provider" text DEFAULT 'openai',
	"default_instrument_type" "instrument_type" DEFAULT 'futures',
	"timezone" text DEFAULT 'UTC',
	"breakeven_threshold" numeric(10, 2) DEFAULT '3.00',
	"currency" text DEFAULT 'USD',
	"theme" text DEFAULT 'terminal',
	"trade_log_columns" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "user_settings_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"clerk_id" text NOT NULL,
	"email" text NOT NULL,
	"name" text,
	"image_url" text,
	"role" "user_role" DEFAULT 'user' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "user_clerk_id_unique" UNIQUE("clerk_id")
);
--> statement-breakpoint
ALTER TABLE "account_group" ADD CONSTRAINT "account_group_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_group_id_account_group_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."account_group"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai_conversation" ADD CONSTRAINT "ai_conversation_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai_message" ADD CONSTRAINT "ai_message_conversation_id_ai_conversation_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."ai_conversation"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "filter_preset" ADD CONSTRAINT "filter_preset_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "strategy" ADD CONSTRAINT "strategy_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "strategy_rule" ADD CONSTRAINT "strategy_rule_strategy_id_strategy_id_fk" FOREIGN KEY ("strategy_id") REFERENCES "public"."strategy"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tag" ADD CONSTRAINT "tag_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trade_execution" ADD CONSTRAINT "trade_execution_trade_id_trade_id_fk" FOREIGN KEY ("trade_id") REFERENCES "public"."trade"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trade_rule_check" ADD CONSTRAINT "trade_rule_check_trade_id_trade_id_fk" FOREIGN KEY ("trade_id") REFERENCES "public"."trade"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trade_rule_check" ADD CONSTRAINT "trade_rule_check_rule_id_strategy_rule_id_fk" FOREIGN KEY ("rule_id") REFERENCES "public"."strategy_rule"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trade_screenshot" ADD CONSTRAINT "trade_screenshot_trade_id_trade_id_fk" FOREIGN KEY ("trade_id") REFERENCES "public"."trade"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trade_tag" ADD CONSTRAINT "trade_tag_trade_id_trade_id_fk" FOREIGN KEY ("trade_id") REFERENCES "public"."trade"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trade_tag" ADD CONSTRAINT "trade_tag_tag_id_tag_id_fk" FOREIGN KEY ("tag_id") REFERENCES "public"."tag"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trade" ADD CONSTRAINT "trade_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trade" ADD CONSTRAINT "trade_account_id_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."account"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_settings" ADD CONSTRAINT "user_settings_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_group_user_id_idx" ON "account_group" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "account_is_default_idx" ON "account" USING btree ("is_default");--> statement-breakpoint
CREATE INDEX "account_group_id_idx" ON "account" USING btree ("group_id");--> statement-breakpoint
CREATE INDEX "account_linked_account_id_idx" ON "account" USING btree ("linked_account_id");--> statement-breakpoint
CREATE INDEX "conversation_user_id_idx" ON "ai_conversation" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "message_conversation_id_idx" ON "ai_message" USING btree ("conversation_id");--> statement-breakpoint
CREATE INDEX "filter_preset_user_id_idx" ON "filter_preset" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "strategy_user_id_idx" ON "strategy" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "strategy_is_active_idx" ON "strategy" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "strategy_rule_strategy_id_idx" ON "strategy_rule" USING btree ("strategy_id");--> statement-breakpoint
CREATE INDEX "strategy_rule_category_idx" ON "strategy_rule" USING btree ("category");--> statement-breakpoint
CREATE INDEX "tag_user_id_idx" ON "tag" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "execution_trade_id_idx" ON "trade_execution" USING btree ("trade_id");--> statement-breakpoint
CREATE INDEX "trade_rule_check_trade_id_idx" ON "trade_rule_check" USING btree ("trade_id");--> statement-breakpoint
CREATE INDEX "trade_rule_check_rule_id_idx" ON "trade_rule_check" USING btree ("rule_id");--> statement-breakpoint
CREATE INDEX "screenshot_trade_id_idx" ON "trade_screenshot" USING btree ("trade_id");--> statement-breakpoint
CREATE INDEX "trade_tag_trade_id_idx" ON "trade_tag" USING btree ("trade_id");--> statement-breakpoint
CREATE INDEX "trade_tag_tag_id_idx" ON "trade_tag" USING btree ("tag_id");--> statement-breakpoint
CREATE INDEX "trade_user_id_idx" ON "trade" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "trade_account_id_idx" ON "trade" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "trade_strategy_id_idx" ON "trade" USING btree ("strategy_id");--> statement-breakpoint
CREATE INDEX "trade_symbol_idx" ON "trade" USING btree ("symbol");--> statement-breakpoint
CREATE INDEX "trade_entry_time_idx" ON "trade" USING btree ("entry_time");--> statement-breakpoint
CREATE INDEX "trade_status_idx" ON "trade" USING btree ("status");--> statement-breakpoint
CREATE INDEX "trade_deleted_at_idx" ON "trade" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX "user_clerk_id_idx" ON "user" USING btree ("clerk_id");