CREATE TYPE "public"."data_quality" AS ENUM('full', 'partial', 'unavailable', 'pending');--> statement-breakpoint
CREATE TABLE "candle_cache" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "candle_cache_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"symbol" text NOT NULL,
	"interval" text NOT NULL,
	"date" timestamp with time zone NOT NULL,
	"bars" text NOT NULL,
	"bar_count" integer NOT NULL,
	"source" text NOT NULL,
	"fetched_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "trade" ADD COLUMN "mae_price" numeric(20, 8);--> statement-breakpoint
ALTER TABLE "trade" ADD COLUMN "mfe_price" numeric(20, 8);--> statement-breakpoint
ALTER TABLE "trade" ADD COLUMN "mae_amount" numeric(20, 2);--> statement-breakpoint
ALTER TABLE "trade" ADD COLUMN "mfe_amount" numeric(20, 2);--> statement-breakpoint
ALTER TABLE "trade" ADD COLUMN "trade_efficiency" numeric(5, 2);--> statement-breakpoint
ALTER TABLE "trade" ADD COLUMN "market_data_quality" "data_quality";--> statement-breakpoint
CREATE UNIQUE INDEX "candle_cache_lookup_idx" ON "candle_cache" USING btree ("symbol","interval","date");--> statement-breakpoint
CREATE INDEX "candle_cache_symbol_idx" ON "candle_cache" USING btree ("symbol");